#!/usr/bin/env bash
set -eu
DIR="$(cd "$(dirname "$0")" && pwd)"; SETUP="$DIR/../architect-setup.sh"; pass=0 fail=0
ok(){ if "$@";then pass=$((pass+1));else echo "FAIL: $*" >&2;fail=$((fail+1));fi;}; eq(){ if [ "$2" = "$3" ];then pass=$((pass+1));else echo "FAIL: $1" >&2;fail=$((fail+1));fi;}; absent(){ if [ ! -e "$2" ]&&[ ! -L "$2" ];then pass=$((pass+1));else echo "FAIL: $1" >&2;fail=$((fail+1));fi;}
TMP="$(mktemp -d "${TMPDIR:-/tmp}/architect-setup.XXXXXX")";trap 'rm -rf "$TMP"' EXIT;OUT="$TMP/out"
R="$TMP/root";mkdir -p "$R";bash "$SETUP" --write-only "$R">"$OUT";eq "two active templates" 2 "$(find "$R/.spaces/architect/templates" -type f|wc -l|tr -d ' ')";for file in adr.md specs.md;do ok test -f "$R/.spaces/architect/templates/$file";done;for file in founding.md draft.md spikes.md;do absent "$file stays package-only" "$R/.spaces/architect/templates/$file";done;absent "schemas stay packaged" "$R/.spaces/architect/schemas";absent "setup leaves draft home absent" "$R/.spaces/architect/drafts";absent "setup leaves spike store absent" "$R/.records/spikes"
printf '\nCUSTOM\n'>>"$R/.spaces/architect/templates/adr.md";sum="$(cksum "$R/.spaces/architect/templates/adr.md")";bash "$SETUP" --write-only "$R">"$OUT";eq "incumbent preserved" "$sum" "$(cksum "$R/.spaces/architect/templates/adr.md")";ok grep -q 'writes=0' "$OUT";absent "no-op leaves draft home absent" "$R/.spaces/architect/drafts";absent "no-op leaves spike store absent" "$R/.records/spikes"
L="$TMP/legacy";mkdir -p "$L/.records/templates/architect";printf x>"$L/.records/templates/architect/adr.md";if bash "$SETUP" --write-only "$L">"$OUT" 2>&1;then fail=$((fail+1));else pass=$((pass+1));fi;ok grep -q '/architect migrate' "$OUT";absent "legacy not adopted" "$L/.spaces/architect/templates/adr.md"
U="$TMP/unsafe";mkdir -p "$U/else";ln -s "$U/else" "$U/.spaces";if bash "$SETUP" --write-only "$U">"$OUT" 2>&1;then fail=$((fail+1));else pass=$((pass+1));fi;absent "unsafe no write" "$U/else/architect"
X="$TMP/exchange";mkdir -p "$X/.spaces/architect" "$X/else";H="$TMP/hook";printf '%s\n' '#!/bin/sh' 'mv "$1/$2/architect" "$1/held"' 'ln -s "$1/else" "$1/$2/architect"'>"$H";chmod +x "$H";if ARCHITECT_SETUP_TEST_AFTER_PREFLIGHT="$H" bash "$SETUP" --write-only "$X">"$OUT" 2>&1;then fail=$((fail+1));else pass=$((pass+1));fi;ok grep -q 'symlinked destination parent' "$OUT";absent "exchange no link write" "$X/else/templates"
P="$TMP/partial";mkdir -p "$P";PH="$TMP/partial-hook";printf '%s\n' '#!/bin/sh' '[ "$4" -eq 1 ] && exit 86' 'exit 0'>"$PH";chmod +x "$PH";if ARCHITECT_SETUP_TEST_AFTER_WRITE="$PH" bash "$SETUP" --write-only "$P">"$OUT" 2>&1;then fail=$((fail+1));else pass=$((pass+1));fi;ok grep -q 'created=.spaces/architect/templates/adr.md' "$OUT";bash "$SETUP" --write-only "$P">"$OUT";eq "partial rerun converges" 2 "$(find "$P/.spaces/architect/templates" -type f|wc -l|tr -d ' ')";absent "partial recovery leaves drafts absent" "$P/.spaces/architect/drafts";absent "partial recovery leaves spikes absent" "$P/.records/spikes"
G="$TMP/git";mkdir -p "$G";git -C "$G" init -q;git -C "$G" config user.name Fixture;git -C "$G" config user.email fixture@example.invalid;printf '# Fixture\n'>"$G/README.md";git -C "$G" add README.md;git -C "$G" commit -qm init;bash "$SETUP" "$G">"$OUT";eq "standalone commit exact paths" "$(printf '%s\n' .spaces/architect/templates/adr.md .spaces/architect/templates/specs.md)" "$(git -C "$G" show --pretty='' --name-only HEAD|sed '/^$/d'|sort)";head="$(git -C "$G" rev-parse HEAD)";bash "$SETUP" "$G">"$OUT";eq "standalone no-op makes no commit" "$head" "$(git -C "$G" rev-parse HEAD)"
B="$TMP/bound";mkdir -p "$B";for asset in founding.md draft.md spikes.md;do if ARCHITECT_SETUP_TEST_ASSET="$asset" bash "$SETUP" --write-only "$B">/dev/null 2>&1;then fail=$((fail+1));else pass=$((pass+1));fi;done;if ARCHITECT_SETUP_TEST_DEST_REL=.spaces/contractor/templates/adr.md bash "$SETUP" --write-only "$B">/dev/null 2>&1;then fail=$((fail+1));else pass=$((pass+1));fi;absent "boundary no writes" "$B/.spaces"
echo "architect setup-test: $pass passed, $fail failed";[ "$fail" -eq 0 ]
