#!/usr/bin/env bash
set -eu
D="$(cd "$(dirname "$0")"&&pwd)";S="$D/../contractor-setup.sh";p=0;f=0;ok(){ if "$@";then p=$((p+1));else echo "FAIL: $*" >&2;f=$((f+1));fi;};eq(){ if [ "$2" = "$3" ];then p=$((p+1));else echo "FAIL: $1" >&2;f=$((f+1));fi;};no(){ if [ ! -e "$2" ]&&[ ! -L "$2" ];then p=$((p+1));else echo "FAIL: $1" >&2;f=$((f+1));fi;};T="$(mktemp -d "${TMPDIR:-/tmp}/contractor-setup.XXXXXX")";trap 'rm -rf "$T"' EXIT;O="$T/out"
R="$T/root";mkdir -p "$R";bash "$S" --write-only "$R">"$O";eq "two templates" 2 "$(find "$R/.spaces/contractor/templates" -type f|wc -l|tr -d ' ')";for file in plan.md roadmap.md;do ok test -f "$R/.spaces/contractor/templates/$file";done;no "no runbook template" "$R/.spaces/contractor/templates/runbook.md";no "no schemas" "$R/.spaces/contractor/schemas";printf '\nCUSTOM\n'>>"$R/.spaces/contractor/templates/plan.md";sum="$(cksum "$R/.spaces/contractor/templates/plan.md")";bash "$S" --write-only "$R">"$O";eq "preserve incumbent" "$sum" "$(cksum "$R/.spaces/contractor/templates/plan.md")";ok grep -q writes=0 "$O"
L="$T/legacy";mkdir -p "$L/.records/templates/contractor";printf x>"$L/.records/templates/contractor/plan.md";if bash "$S" --write-only "$L">"$O" 2>&1;then f=$((f+1));else p=$((p+1));fi;ok grep -q '/contractor migrate' "$O";no "legacy not adopted" "$L/.spaces/contractor/templates/plan.md"
U="$T/unsafe";mkdir -p "$U/else";ln -s "$U/else" "$U/.spaces";if bash "$S" --write-only "$U">"$O" 2>&1;then f=$((f+1));else p=$((p+1));fi;no "unsafe no write" "$U/else/contractor"
X="$T/exchange";mkdir -p "$X/.spaces/contractor" "$X/else";H="$T/h";printf '%s\n' '#!/bin/sh' 'mv "$1/$2/contractor" "$1/held"' 'ln -s "$1/else" "$1/$2/contractor"'>"$H";chmod +x "$H";if CONTRACTOR_SETUP_TEST_AFTER_PREFLIGHT="$H" bash "$S" --write-only "$X">"$O" 2>&1;then f=$((f+1));else p=$((p+1));fi;ok grep -q 'symlinked destination parent' "$O";no "exchange no write" "$X/else/templates"
P="$T/partial";mkdir -p "$P";PH="$T/partial-hook";printf '%s\n' '#!/bin/sh' '[ "$4" -eq 1 ] && exit 86' 'exit 0'>"$PH";chmod +x "$PH";if CONTRACTOR_SETUP_TEST_AFTER_WRITE="$PH" bash "$S" --write-only "$P">"$O" 2>&1;then f=$((f+1));else p=$((p+1));fi;ok grep -q 'created=.spaces/contractor/templates/plan.md' "$O";bash "$S" --write-only "$P">"$O";eq "partial rerun converges" 2 "$(find "$P/.spaces/contractor/templates" -type f|wc -l|tr -d ' ')"
G="$T/git";mkdir -p "$G";git -C "$G" init -q;git -C "$G" config user.name Fixture;git -C "$G" config user.email fixture@example.invalid;printf '# Fixture\n'>"$G/README.md";git -C "$G" add README.md;git -C "$G" commit -qm init;bash "$S" "$G">"$O";eq "standalone commit exact paths" "$(printf '%s\n' .spaces/contractor/templates/plan.md .spaces/contractor/templates/roadmap.md)" "$(git -C "$G" show --pretty='' --name-only HEAD|sed '/^$/d'|sort)";head="$(git -C "$G" rev-parse HEAD)";bash "$S" "$G">"$O";eq "standalone no-op makes no commit" "$head" "$(git -C "$G" rev-parse HEAD)"
B="$T/bound";mkdir -p "$B";if CONTRACTOR_SETUP_TEST_ASSET=runbook.md bash "$S" --write-only "$B">/dev/null 2>&1;then f=$((f+1));else p=$((p+1));fi;if CONTRACTOR_SETUP_TEST_DEST_REL=.spaces/architect/templates/plan.md bash "$S" --write-only "$B">/dev/null 2>&1;then f=$((f+1));else p=$((p+1));fi;no "boundary no writes" "$B/.spaces"
echo "contractor setup-test: $p passed, $f failed";[ "$f" -eq 0 ]
