use std::collections::{BTreeMap, BTreeSet};
use std::convert::TryInto;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

const INPUTS: [(&str, &str); 5] = [
    ("UnicodeData.txt", "2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c"),
    ("CompositionExclusions.txt", "2f239196ef3b5b61db5cc476e9bd80f534d15aa1b74e1be1dea5d042a344c85f"),
    ("DerivedNormalizationProps.txt", "71fd6a206a2c0cdd41feb6b7f656aa31091db45e9cedc926985d718397f9e488"),
    ("NormalizationTest.txt", "5019ffd530751a741900c849c0e010332f142a3612234639bd200b82138a87db"),
    ("LICENSE.txt", "e7a93b009565cfce55919a381437ac4db883e9da2126fa28b91d12732bc53d96"),
];

fn main() {
    let mut args = env::args_os().skip(1);
    let input = PathBuf::from(args.next().expect("usage: generate_unicode17 <input-dir> <output>"));
    let output = PathBuf::from(args.next().expect("usage: generate_unicode17 <input-dir> <output>"));
    assert!(args.next().is_none(), "usage: generate_unicode17 <input-dir> <output>");
    for (name, expected) in INPUTS {
        let bytes = fs::read(input.join(name))
            .unwrap_or_else(|error| panic!("read {}: {}", name, error));
        let actual = hex(&sha256(&bytes));
        assert_eq!(actual, expected, "refusing unpinned Unicode input {}", name);
    }
    let unicode_data = fs::read_to_string(input.join("UnicodeData.txt")).unwrap();
    let derived = fs::read_to_string(input.join("DerivedNormalizationProps.txt")).unwrap();
    let exclusions = fs::read_to_string(input.join("CompositionExclusions.txt")).unwrap();

    let mut ccc = BTreeMap::new();
    let mut decomposition = BTreeMap::new();
    for line in unicode_data.lines().filter(|line| !line.is_empty()) {
        let fields: Vec<_> = line.split(';').collect();
        let cp = u32::from_str_radix(fields[0], 16).unwrap();
        let class: u8 = fields[3].parse().unwrap();
        if class != 0 {
            ccc.insert(cp, class);
        }
        let mapping = fields[5];
        if !mapping.is_empty() && !mapping.starts_with('<') {
            decomposition.insert(cp, codepoints(mapping));
        }
    }

    let mut excluded = BTreeSet::new();
    for line in exclusions.lines() {
        let value = line.split('#').next().unwrap().trim();
        if !value.is_empty() {
            insert_range(&mut excluded, value);
        }
    }
    for line in derived.lines() {
        let value = line.split('#').next().unwrap().trim();
        if value.is_empty() {
            continue;
        }
        let fields: Vec<_> = value.split(';').map(str::trim).collect();
        if fields.get(1) == Some(&"Full_Composition_Exclusion") {
            insert_range(&mut excluded, fields[0]);
        }
    }

    let mut mappings = Vec::new();
    for line in derived.lines() {
        let value = line.split('#').next().unwrap().trim();
        if value.is_empty() {
            continue;
        }
        let fields: Vec<_> = value.split(';').map(str::trim).collect();
        if fields.get(1) != Some(&"NFKC_CF") {
            continue;
        }
        let (start, end) = parse_range(fields[0]);
        mappings.push((start, end, codepoints(fields.get(2).copied().unwrap_or_default())));
    }

    let mut composition = BTreeMap::new();
    for (&composed, parts) in &decomposition {
        if parts.len() == 2 && !excluded.contains(&composed) && ccc.get(&parts[0]).copied().unwrap_or(0) == 0 {
            composition.insert((parts[0], parts[1]), composed);
        }
    }

    let generated = render(&mappings, &decomposition, &ccc, &composition);
    fs::write(&output, generated).unwrap_or_else(|error| panic!("write {}: {error}", output.display()));
    let status = Command::new("rustfmt")
        .arg("--edition")
        .arg("2021")
        .arg(&output)
        .status()
        .unwrap_or_else(|error| panic!("run rustfmt: {}", error));
    assert!(status.success(), "rustfmt failed for {}", output.display());
}

fn render(
    mappings: &[(u32, u32, Vec<u32>)],
    decomposition: &BTreeMap<u32, Vec<u32>>,
    ccc: &BTreeMap<u32, u8>,
    composition: &BTreeMap<(u32, u32), u32>,
) -> String {
    let mut out = String::new();
    writeln!(out, "// @generated by tools/generate_unicode17.rs; Unicode 17.0.0.").unwrap();
    writeln!(out, "// Do not hand-edit. Regenerate only from the pinned tests/data/unicode-17 inputs.\n").unwrap();
    writeln!(out, "#[cfg(test)]\npub(crate) const UNICODE_VERSION: &str = \"17.0.0\";").unwrap();
    writeln!(out, "#[cfg(test)]\npub(crate) const NFKC_CF_RANGE_COUNT: usize = {};\n", mappings.len()).unwrap();
    writeln!(out, "const NFKC_CF: &[(u32, u32, &[u32])] = &[").unwrap();
    for (start, end, values) in mappings {
        writeln!(out, "    (0x{start:X}, 0x{end:X}, &{}),", slice(values)).unwrap();
    }
    writeln!(out, "];\n").unwrap();
    writeln!(out, "const DECOMPOSITION: &[(u32, &[u32])] = &[").unwrap();
    for (cp, values) in decomposition {
        writeln!(out, "    (0x{cp:X}, &{}),", slice(values)).unwrap();
    }
    writeln!(out, "];\n").unwrap();
    writeln!(out, "const COMBINING_CLASS: &[(u32, u8)] = &[").unwrap();
    for (cp, class) in ccc {
        writeln!(out, "    (0x{cp:X}, {class}),").unwrap();
    }
    writeln!(out, "];\n").unwrap();
    writeln!(out, "const COMPOSITION: &[((u32, u32), u32)] = &[").unwrap();
    for ((first, second), composed) in composition {
        writeln!(out, "    ((0x{first:X}, 0x{second:X}), 0x{composed:X}),").unwrap();
    }
    writeln!(out, "];\n").unwrap();
    out.push_str(RUNTIME);
    out
}

const RUNTIME: &str = r#"pub(crate) fn to_nfkc_casefold(value: &str) -> String {
    let mut mapped = Vec::new();
    for ch in value.chars() {
        let cp = ch as u32;
        match NFKC_CF.binary_search_by(|(start, end, _)| {
            if cp < *start { std::cmp::Ordering::Greater } else if cp > *end { std::cmp::Ordering::Less } else { std::cmp::Ordering::Equal }
        }) {
            Ok(index) => mapped.extend_from_slice(NFKC_CF[index].2),
            Err(_) => mapped.push(cp),
        }
    }
    normalize_codepoints(mapped)
}

#[cfg(test)]
pub(crate) fn normalize_nfc(value: &str) -> String {
    normalize_codepoints(value.chars().map(|ch| ch as u32).collect())
}

fn normalize_codepoints(mapped: Vec<u32>) -> String {
    let mut decomposed = Vec::new();
    for cp in mapped { decompose(cp, &mut decomposed); }
    reorder(&mut decomposed);
    compose(&decomposed).into_iter().filter_map(char::from_u32).collect()
}

fn decompose(cp: u32, out: &mut Vec<u32>) {
    const S_BASE: u32 = 0xAC00;
    const L_BASE: u32 = 0x1100;
    const V_BASE: u32 = 0x1161;
    const T_BASE: u32 = 0x11A7;
    const L_COUNT: u32 = 19;
    const V_COUNT: u32 = 21;
    const T_COUNT: u32 = 28;
    const N_COUNT: u32 = V_COUNT * T_COUNT;
    const S_COUNT: u32 = L_COUNT * N_COUNT;
    let index = cp.wrapping_sub(S_BASE);
    if index < S_COUNT {
        out.push(L_BASE + index / N_COUNT);
        out.push(V_BASE + (index % N_COUNT) / T_COUNT);
        let trail = index % T_COUNT;
        if trail != 0 { out.push(T_BASE + trail); }
    } else if let Ok(index) = DECOMPOSITION.binary_search_by_key(&cp, |(value, _)| *value) {
        for part in DECOMPOSITION[index].1 { decompose(*part, out); }
    } else {
        out.push(cp);
    }
}

fn combining_class(cp: u32) -> u8 {
    COMBINING_CLASS.binary_search_by_key(&cp, |(value, _)| *value).map_or(0, |index| COMBINING_CLASS[index].1)
}

fn reorder(values: &mut [u32]) {
    for index in 1..values.len() {
        let class = combining_class(values[index]);
        if class == 0 { continue; }
        let mut cursor = index;
        while cursor > 0 {
            let previous = combining_class(values[cursor - 1]);
            if previous == 0 || previous <= class { break; }
            values.swap(cursor - 1, cursor);
            cursor -= 1;
        }
    }
}

#[allow(clippy::manual_is_multiple_of)]
fn compose_pair(first: u32, second: u32) -> Option<u32> {
    const S_BASE: u32 = 0xAC00;
    const L_BASE: u32 = 0x1100;
    const V_BASE: u32 = 0x1161;
    const T_BASE: u32 = 0x11A7;
    const L_COUNT: u32 = 19;
    const V_COUNT: u32 = 21;
    const T_COUNT: u32 = 28;
    const N_COUNT: u32 = V_COUNT * T_COUNT;
    const S_COUNT: u32 = L_COUNT * N_COUNT;
    let l = first.wrapping_sub(L_BASE);
    let v = second.wrapping_sub(V_BASE);
    if l < L_COUNT && v < V_COUNT { return Some(S_BASE + (l * V_COUNT + v) * T_COUNT); }
    let s = first.wrapping_sub(S_BASE);
    let t = second.wrapping_sub(T_BASE);
    if s < S_COUNT && s % T_COUNT == 0 && t > 0 && t < T_COUNT { return Some(first + t); }
    COMPOSITION.binary_search_by_key(&(first, second), |(pair, _)| *pair).ok().map(|index| COMPOSITION[index].1)
}

fn compose(values: &[u32]) -> Vec<u32> {
    let Some(&first) = values.first() else { return Vec::new(); };
    let mut out = vec![first];
    let mut starter = 0usize;
    let mut last_class = combining_class(first);
    for &cp in &values[1..] {
        let class = combining_class(cp);
        if let Some(composed) = compose_pair(out[starter], cp).filter(|_| last_class == 0 || last_class < class) {
            out[starter] = composed;
        } else {
            if class == 0 { starter = out.len(); }
            out.push(cp);
            last_class = class;
        }
    }
    out
}
"#;

fn slice(values: &[u32]) -> String {
    let mut out = String::from("[");
    for (index, value) in values.iter().enumerate() {
        if index != 0 { out.push_str(", "); }
        write!(out, "0x{value:X}").unwrap();
    }
    out.push(']');
    out
}

fn codepoints(value: &str) -> Vec<u32> {
    value
        .split_whitespace()
        .map(|part| u32::from_str_radix(part, 16).unwrap())
        .collect()
}

fn parse_range(value: &str) -> (u32, u32) {
    if let Some((start, end)) = value.split_once("..") {
        (u32::from_str_radix(start, 16).unwrap(), u32::from_str_radix(end, 16).unwrap())
    } else {
        let value = u32::from_str_radix(value, 16).unwrap();
        (value, value)
    }
}

fn insert_range(set: &mut BTreeSet<u32>, value: &str) {
    let (start, end) = parse_range(value);
    set.extend(start..=end);
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}

fn sha256(input: &[u8]) -> [u8; 32] {
    const K: [u32; 64] = [
        0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,
        0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,
        0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,
        0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,
        0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,
        0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,
        0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,
        0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2,
    ];
    let mut h = [0x6a09e667u32,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19];
    let bit_len = (input.len() as u64) * 8;
    let mut message = input.to_vec();
    message.push(0x80);
    while message.len() % 64 != 56 { message.push(0); }
    message.extend_from_slice(&bit_len.to_be_bytes());
    for chunk in message.chunks_exact(64) {
        let mut w = [0u32; 64];
        for (index, bytes) in chunk.chunks_exact(4).enumerate() { w[index] = u32::from_be_bytes(bytes.try_into().unwrap()); }
        for index in 16..64 {
            let s0 = w[index-15].rotate_right(7) ^ w[index-15].rotate_right(18) ^ (w[index-15] >> 3);
            let s1 = w[index-2].rotate_right(17) ^ w[index-2].rotate_right(19) ^ (w[index-2] >> 10);
            w[index] = w[index-16].wrapping_add(s0).wrapping_add(w[index-7]).wrapping_add(s1);
        }
        let [mut a,mut b,mut c,mut d,mut e,mut f,mut g,mut hh] = h;
        for index in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ ((!e) & g);
            let t1 = hh.wrapping_add(s1).wrapping_add(ch).wrapping_add(K[index]).wrapping_add(w[index]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let t2 = s0.wrapping_add(maj);
            hh=g; g=f; f=e; e=d.wrapping_add(t1); d=c; c=b; b=a; a=t1.wrapping_add(t2);
        }
        for (state, value) in h.iter_mut().zip([a,b,c,d,e,f,g,hh]) { *state = state.wrapping_add(value); }
    }
    let mut out = [0u8; 32];
    for (slot, value) in out.chunks_exact_mut(4).zip(h) { slot.copy_from_slice(&value.to_be_bytes()); }
    out
}
